### ISSUE TITLE
Configure MongoDB

### ISSUE THREAD

**Issue by juggler39** [juggler39/ais-chess#13]
create collections:

1. Schemas for:
- [x] User 
- [x] Opened Games ( with game chat )
- [x] Finished Games
- [x] Global chat
2. ...

**Comment by juggler39** [comment]
How are you going to store the open calls? Could you create a couple of open calls, which will use to test the frontend part.

**Comment by TapeGhad** [comment]
Actually, if we talk about Configuration of MongoDB, it's resolved for now. Of course, it will be modificated during the development process, but basic functionality is provided. Now I need to work with routes to get it work fine with frontend, but this is another task :)

**Comment by TapeGhad** [comment]
> How are you going to store the open calls? Could you create a couple of open calls, which will use to test the frontend part.

For now, of course, it's possible to create them, but to provide access to them from the frontend server, I'll need to define and configure all necessary routes. Tomorrow, I hope, I'll do it.

**Comment by TapeGhad** [comment]
Test
