### ISSUE TITLE
Avatar 

### ISSUE THREAD

**Issue by juggler39** [juggler39/ais-chess#193]
The avatar picture doesn't appear on the account page.

**Comment by juggler39** [comment]
If the user doesn't have any avatar we get this:
![image](https://user-images.githubusercontent.com/61351959/97685197-a679f780-1aa1-11eb-8f08-b3440fab68c4.png)

**Comment by tanyashulha** [comment]
I changed response and you now have old picteru view. Just reload your avatar

**Comment by juggler39** [comment]
If the user has an avater, it works fine:
![image](https://user-images.githubusercontent.com/61351959/97704982-fcf42f80-1abb-11eb-8205-536f4eca85dd.png)
But if he dosn't, then we get this:
![image](https://user-images.githubusercontent.com/61351959/97705011-07162e00-1abc-11eb-9750-3aede152c070.png)
