### ISSUE TITLE
socket.io errors in the console

### ISSUE THREAD

**Issue by juggler39** [juggler39/ais-chess#20]
We are getting a huge amount of socket.io errors in the console:

![image](https://user-images.githubusercontent.com/61351959/94829637-05990d80-040b-11eb-9b22-4b5e9a89f777.png)

Please consider, how we can aviod them. I propose to use separate branches for such experiments.

**Comment by TapeGhad** [comment]
Yes, I saw it too. As I understand (and see) the problem is that socket.io try to use localhost 3030 ( when our backend is running on 8000)

**Comment by dzianisshupenka** [comment]
I fix it, that's was a server problem
