### ISSUE TITLE
Contact page

### ISSUE THREAD

**Issue by juggler39** [juggler39/ais-chess#203]
The contact page doesn't exist. Here must be some information about our team.
![image](https://user-images.githubusercontent.com/61351959/97601184-97983400-1a12-11eb-9b38-ee09431491da.png)

**Comment by tanyashulha** [comment]
Maybe we make page "About us"(about developers, who made chess portal)  instead "Contact", for example, with our photo, some information and so on?

**Comment by juggler39** [comment]
Let it be just "About". We can give some information about the project and our team.
