### ISSUE TITLE
Implement rating system

### ISSUE THREAD

**Issue by juggler39** [juggler39/ais-chess#211]
Every new player gets the rating 1200. Every play changes the rating according to the ELO-system:

https://en.wikipedia.org/wiki/Elo_rating_system

- [x] calculate the rating
- [x] add a rating field to the profile
- [ ] create a rating page

**Comment by juggler39** [comment]
Do we need a whole page for the rating? Won't it be too ugly?

**Comment by TapeGhad** [comment]
Maybe, we can hold this list of rating in home page or even lobby with pagination.

**Comment by TapeGhad** [comment]
Because, if we create a seperate page for it, so we'll need to decorate it with the gold medal of the first place, silver of the second and so on, something like that. To make this page look like a real rating page

**Comment by juggler39** [comment]
Exactly. So, top 10 on the front page will be sufficient for now.
