### ISSUE TITLE
socket.io server-side setup

### ISSUE THREAD

**Issue by dzianisshupenka** [juggler39/ais-chess#26]
Server-side setup socket.io for private chats for each game

- [x] New game
- [x] Game History
- [x] Playrs chat
- [x] Global chat

**Comment by paulmhan** [comment]
Are you looking to change all your express routes to socket, or additionally add a chat room feature using socket?

**Comment by paulmhan** [comment]
If the latter, I would love to help you create that, I have a lot of experience using socket and building chat applciations.

**Comment by dzianisshupenka** [comment]
> If the latter, I would love to help you create that, I have a lot of experience using socket and building chat applciations.


Sorry, this is our course / study project, we don't need help
