### ISSUE TITLE
Game creating process

### ISSUE THREAD

**Issue by juggler39** [juggler39/ais-chess#50]
Let's discuss, what happens, when the second player chooses a created game.

- [x] The player is redirected to a game page with game ID in URL, like this:
![image](https://user-images.githubusercontent.com/61351959/95299516-24b9f400-087e-11eb-8a68-408c594d10a5.png)

- [x] An object in vuex ist created with the following data:
{
gameID: GameID,
isOpen: true,
timeControl: ,
playerWhite: playerID,
playerBlack: playerID,
gameHistory: (we need to have the history separate, because now we use the same history for both computer and human play
an when we switch between pages, the history doesn't change),
result: null,
do we need some other data here?
}
- [x] on the server side the game remains in the OpenGames with the flag "isOpen = true".
If the user reloads the page, the game history of the runnung game loads from the server.

- [x] At the game end the result (1:0, 1/2:1/2, 0:1) is stored into the object and sent to the server. The result and gameID is sent to the server. The game is deleted from the openGames and relocated to the finishedGames.

Please share your thoughts, what else we have to do.

**Comment by dzianisshupenka** [comment]
Should we save the history of the game with AI?

**Comment by dzianisshupenka** [comment]
I think when we create a new game, we should create a full object of the game as you wrote, and add fields like "isOpen", with "true" default value. When the player chose this game, we change this flag to false and remove the game from OpenGames list. And maybe one more field like "inProgress" or "isPlaying" with "true" when the game start, and false when game finished

**Comment by dzianisshupenka** [comment]
Today I'm gonna split the game history.

**Comment by TapeGhad** [comment]
1. About the second point, I think field timeToGo ( or something like that ) should be too in vuex store.
2. I agree with Dzianis about field isOpen. When second user connect to the game, flag is false and game will dissapear from game list. What about field inProgress, may be it's unuseful, because if isOpen = false, game is automatically in progress until it finised and removed to FinishedGames collection.
3. In my plan, FinishedGame collection is only for finished game (where the winner is determined), otherwise it will be in OpenGames coll.
4. In the fourth point, I think gameID and result will be enough. All other will already exists and saved. We need gameID to find it in OpenGames, duplicate info and save in FinishedGames. After that, it will be delete from OpenGames.

**Comment by TapeGhad** [comment]
_At the game end the result (1:0, 1/2:1/2, 0:1)_ 
What does 1/2:1/2 mean?)

**Comment by juggler39** [comment]
> Should we save the history of the game with AI?

We don't need to save it to the database, but it must be available until the new game with AI is started.
The player needs to have a possibility to analyse his game.

**Comment by juggler39** [comment]
> I think when we create a new game, we should create a full object of the game as you wrote, and add fields like "isOpen", with "true" default value. When the player chose this game, we change this flag to false and remove the game from OpenGames list. And maybe one more field like "inProgress" or "isPlaying" with "true" when the game start, and false when game finished

OK. I add the flag "isOpen" in the initial post. I am not sure about the other flag. If the game isOpen, but has no result, it is in progress. Isn't it?

**Comment by juggler39** [comment]
> 1. About the second point, I think field timeToGo ( or something like that ) should be too in vuex store.

Yes. 

> 2. I agree with Dzianis about field isOpen. When second user connect to the game, flag is false and game will dissapear from game list. What about field inProgress, may be it's unuseful, because if isOpen = false, game is automatically in progress until it finised and removed to FinishedGames collection.

Agree

> 3. In my plan, FinishedGame collection is only for finished game (where the winner is determined), otherwise it will be in OpenGames coll.

OK

> 4. In the fourth point, I think gameID and result will be enough. All other will already exists and saved. We need gameID to find it in OpenGames, duplicate info and save in FinishedGames. After that, it will be delete from OpenGames.

OK

I will update the initial post withthis information

**Comment by juggler39** [comment]
> _At the game end the result (1:0, 1/2:1/2, 0:1)_
> What does 1/2:1/2 mean?)

It means a draw. Each player gets half a point

**Comment by dzianisshupenka** [comment]
I think we should have a Running games collections, where we should keep info about players, moves, private chat, maybe timer info. Because If we remove the game from open games after the game start, where we will keep this info. We need this info during the game process

**Comment by dzianisshupenka** [comment]
I have a proposal to add to user profile in the database a field "Active game".For example, if the user disconnects and reconnect if he has an active game we automatically redirect him to his active game. When the game ends we clear this field.

**Comment by TapeGhad** [comment]
> I have a proposal to add to user profile in the database a field "Active game".For example, if the user disconnects and reconnect if he has an active game we automatically redirect him to his active game. When the game ends we clear this field.

Agree, will store here a gameID or null.

**Comment by TapeGhad** [comment]
> I think we should have a Running games collections, where we should keep info about players, moves, private chat, maybe timer info. Because If we remove the game from open games after the game start, where we will keep this info. We need this info during the game process

As I planned, we don't remove game from openGames until it **finished**. We just only change its flag isOpen so it won't be shown in lobby. That's why another coll, in my opinion, is unuseful.
