### ISSUE TITLE
Add user to OpenGame when choose a game in lobby

### ISSUE THREAD

**Issue by TapeGhad** [juggler39/ais-chess#82]
For now, as I see, when we click on game in lobby, this is automatically disapear because of isOpen filed set to false. But we don't save ID of another user, his name and color.

**Comment by TapeGhad** [comment]
Moreover, if creator choose his game, it shouldn't write the same person as the second player and set isOpen to false.

**Comment by TapeGhad** [comment]
And unauthorized user mustn't create games.

**Comment by dzianisshupenka** [comment]
> Moreover, if creator choose his game, it shouldn't write the same person as the second player and set isOpen to false.

You cant choose your game in the list of open games, we check it in selectGame method in Lobby.vue

**Comment by TapeGhad** [comment]
> > Moreover, if creator choose his game, it shouldn't write the same person as the second player and set isOpen to false.
> 
> You cant choose your game in the list of open games, we check it in selectGame method in Lobby.vue

Yes, I saw)
